
dataset_name = "cdc_diabetes" 
target_col_name = "Diabetes_binary"
prediction_task = "binary_classification"  # ,regression,  multiclass_classification, binary_classification
models_list = ["tabsyn",] # ["tabsyn","tabddpm","codi","great"]
runs = ['A','B',]
date = "20251114"  # yyyymmdd


[local]
data_path = "/Users/leec/Documents/datasets"
output_path = "/Users/leec/Documents/synthetics"
local_computer_name = ["leeputer.local","Mac.routerlogin.net"]

[moriah]
data_path = "/sci/labs/yuvalb/lee.carlin/tabular_datasets"
output_path = "/sci/labs/yuvalb/lee.carlin/synthetics"
moriah_node_types = ["catfish","salmon","goldfish","dogfish","glacier"]

## petfinder_tab (is_adopted), credit_taiwan (default), adult_census (is_high_income), 
##  diabetes_130us (readmitted),  cdc_diabetes (Diabetes_binary), home_credit (TARGET)