

dataset_name = "petfinder_tab" 
target_col_name = "is_adopted"
prediction_task = "binary_classification"  # ,regression,  multiclass_classification, binary_classification
models_list = ["tabsyn","tabddpm","codi","great"] # ["tabsyn","tabddpm","codi","great"]
runs = ['A','B','C']
date = "20251112"  # yyyymmdd


[local]
data_path = "/Users/leec/Documents/datasets"
output_path = "/Users/leec/Documents/synthetics"
local_computer_name = ["leeputer.local","Mac.routerlogin.net"]

[moriah]
data_path = "/sci/labs/yuvalb/lee.carlin/tabular_datasets"
output_path = "/sci/labs/yuvalb/lee.carlin/synthetics"
moriah_node_types = ["catfish","salmon","goldfish","dogfish","glacier"]