parent_dir = "configs/credit_taiwan"
model_save_path = "ckpt/credit_taiwan"
sample_save_path = "sampled/credit_taiwan"
real_data_path = "data/credit_taiwan"

num_numerical_features = 20
model_type = "mlp"
task_type = "binclass"

[model_params]
num_classes = 2
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    1024,
    2048,
    2048,
    1024,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 100000
lr = 0.001809824563637657
weight_decay = 5e-4
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "mean"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 2247
batch_size = 1000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"